import 'skill_category.dart';

class GuideStep {
  final int step;
  final String text;

  const GuideStep({required this.step, required this.text});

  factory GuideStep.fromJson(Map<String, dynamic> json, int fallbackIndex) {
    final dynamic rawStep = json['step'];
    final int parsed = rawStep is int
        ? rawStep
        : int.tryParse('${rawStep ?? ''}') ?? fallbackIndex;
    return GuideStep(step: parsed, text: (json['text'] ?? '').toString().trim());
  }

  Map<String, dynamic> toJson() => {'step': step, 'text': text};
}

/// A step-by-step guide generated by Haiku. The [category] is NOT part of the
/// LLM JSON — it comes from the opportunity that spawned the guide and is stored
/// alongside the JSON in guide_cache, so it must be supplied when reconstructing.
class Guide {
  final String title;
  final SkillCategory category;
  final List<GuideStep> steps;
  final bool fireWarning;
  final String? legalNote;

  const Guide({
    required this.title,
    required this.category,
    required this.steps,
    required this.fireWarning,
    required this.legalNote,
  });

  factory Guide.fromJson(
    Map<String, dynamic> json, {
    required SkillCategory category,
  }) {
    final List<dynamic> rawSteps = (json['steps'] as List<dynamic>?) ?? const [];
    final steps = <GuideStep>[];
    for (var i = 0; i < rawSteps.length; i++) {
      final item = rawSteps[i];
      if (item is Map<String, dynamic>) {
        steps.add(GuideStep.fromJson(item, i + 1));
      } else if (item != null) {
        // Tolerate a plain string step.
        steps.add(GuideStep(step: i + 1, text: item.toString().trim()));
      }
    }
    final note = json['legal_note'];
    return Guide(
      title: (json['title'] ?? '').toString().trim(),
      category: category,
      steps: steps,
      fireWarning: json['fire_warning'] == true,
      legalNote: (note == null || '$note'.trim().isEmpty) ? null : '$note'.trim(),
    );
  }

  Map<String, dynamic> toJson() => {
        'title': title,
        'steps': steps.map((s) => s.toJson()).toList(),
        'fire_warning': fireWarning,
        'legal_note': legalNote,
      };

  bool get isForaging => category == SkillCategory.foraging;
}
