import 'skill_category.dart';

/// A single practice opportunity card on the Now tab, as generated by Haiku.
class Opportunity {
  final SkillCategory category;
  final String title;
  final String description;
  final bool fireWarning;

  const Opportunity({
    required this.category,
    required this.title,
    required this.description,
    required this.fireWarning,
  });

  factory Opportunity.fromJson(Map<String, dynamic> json) {
    return Opportunity(
      category: skillCategoryFromString(json['skill_category'] as String?),
      title: (json['title'] ?? '').toString().trim(),
      description: (json['description'] ?? '').toString().trim(),
      fireWarning: json['fire_warning'] == true,
    );
  }

  Map<String, dynamic> toJson() => {
        'skill_category': category.id,
        'title': title,
        'description': description,
        'fire_warning': fireWarning,
      };
}
